### ISSUE TITLE
Spark jobs size increasing double for same dataframe for same proration

### ISSUE THREAD

**Issue by nagarajmmu** [qwshen/spark-flight-connector#4] opened 2022-11-19 02:13 UTC
Hi Wayne

I have parquet file in Dremio, I have used below query to read it in Spark setup.
_val df=spark.read.option("host", "[SPARK_IP]").option("port", 32010).option("tls.enabled", false).option("tls.verifyServer", false).option("user", "user").option("password", "password").option("partition.size", 320).option("partition.byColumn", "COLUMN1").flight(""""dremio_space"."file"""").filter("COLUMN == 22")_

After above query, I have executed df.count, 320 spark jobs are running to get count (count=15), when I ran df.count second time, 640 jobs run to get count (count=30), again I ran df.count, 960 jobs run to get count (count=45).
Do you have any idea, why jobs are increasing and count also increasing, after each execution. 
Same issue happened, when I tried to run Group BY on dataframe.

Please let me know, what should I do to fic this issue.

Thanks
Nagaraja M M

**Comment by qwshen** [comment] 2022-11-19 04:25
Per your case, can you run the following code?

val df=spark.read.option("host", "[SPARK_IP]").option("port", 32010).option("tls.enabled", false).option("user", "user").option("password", "password").flight(""""dremio_space"."file"""").filter("COLUMN == 22")

Then
df.count

Go to Dremio web console, check the query logs and see what query was submitted to Dremio?
Run df.count again, and see what query submitted to Dremio?

Run the submitted query in Dremio web console multiple times?

Thanks
Wayne

**Comment by nagarajmmu** [comment] 2022-11-21 23:21
Hi Wayne

I have used query without "partition.byColumn" it works fine and fast.
But "partition.byColumn" help to load big data very fast, but it will hit dremio more than a 100 times.
If this is the case, how to manipulate the data in data frame.
 
When we should use "partition.byColumn" and when we should avoid "partition.byColumn".
Or let me know if there is reference for such scenario. 
Please let me know.

Thanks
Nagaraj M M

**Comment by qwshen** [comment] 2022-11-22 00:29
The partition.size and partition.byColumn control how many partitions will be in the dataframe. You get a single dataframe so you manipulate it as normal.

When a dataset being loaded from Dremio is a large one such as millions+ rows, then you need to provide values for this two properties (with current version of Dremio), otherwise you may get "Out of Memory" issue. In your current case (count = 15), you don't need the partitioning.

However df.count should only submit one query to Dremio so there should be only one Dremio job instead of 320 jobs due to the push-down of count.

Hope this helps.

Thanks
Wayne

**Comment by qwshen** [comment] 2022-11-23 16:09
This behavior is by design - "Multiple Jobs submitted to Dremio when custom partitioning is enabled", so closing this ticket.

@nagarajmmu if you still see unusual behavior from the connector, please submit another ticket.

Thanks
Wayne

**Closed as completed by qwshen** 2022-11-23 16:09 UTC
